<?php
// Sistema de traducciones.
$Club = json(array(
    'NombreCompleto' => 'Club de Judo Kazoku',
    'NombreCorto' => 'Club Kazoku',
    'Nombre' => 'Kazoku',
    'Lema' => 'Kazoku significa familia en Japonés',
    'SitioWeb' => 'clubkazoku.es',
    'SitioPrincipal' => 'Málaga',
    'Sede1' => 'Málaga',
    'Sede2' => 'Fuengirola',
    'Presdente' => 'Jose David',
    'Profesor1' => 'Jose David',
    'CorreoAdministracion' => 'administracion@clubkazoku.es',
    'Mailto' => '<a class="link" href="mailto:administracion@clubkazoku.es">administracion@clubkazoku.es</a>',
    'CorreoDesarrollo' => 'desarrollo@clubkazoku.es',
));
$Mensajes = json(array(
    'Mantenimiento' => 'Estamos en mantenimiento, disculpe las molestias',
    'Error' => 'Ooops... Ha ocurrido un error, inténtelo de nuevo más tarde',
    'NoDisponible' => 'Esto no está disponible',
    'Proximamente' => 'Próximamente',
    '404' => 'No encontrado... ¿Seguro que existe?',
    '500' => 'Intentelo de nuevo, si persiste, contacte al 609914731',
    'Bienvenida' => 'Bienvenid@ al Servicio Web del Club Kazoku',
    'Contacto' => '¡Contáctanos!',
    'privacidad' => 'Política de privacidad',
    'Noticias' => 'Noticias',
    'NoticiasDestacadas' => 'Noticias destacadas',
    'NoticiasUltimas' => 'Últimas Noticias',
    'VerNoticias' => 'Ver todas las noticias',
    'Galeria' => 'Galería',
    'DondeEstamos' => '¿Dónde estamos?',
    'ElClub' => 'El club',
    'Blog' => 'El Blog',
    'Carrito' => 'Carrito',
    'VerCarrito' => 'Ver Carrito',
    'VerCompra' => 'Ver Compra',
    'Catalogo' => 'Catálogo',
    'Tienda' => 'Tienda',
    'TiendaDeportiva' => 'Tienda Deportiva',
    'TiendaOnline' => 'Tienda Online',
    'InformateNovedades' => 'Infórmate de las novedades',
    'CompraEquipacion' => 'Compra tu judogui',
    'Campeonatos' => 'Campeonatos',
    'NoticiasResultados' => 'Noticias y resultados',
    'VisitaNuestra' => 'Visita nuestra',
    'TodaInformacion' => 'Toda la información',
    'RRSS' => 'Nuestras redes',
    'TuCuenta' => 'Tu cuenta',
    'TuCorreo' => 'Tu correo',
    'TuMensaje' => 'Tu mensaje',
    'Contra' => 'Contraseña',
    'RepContra' => 'Repetir Contraseña',
    'CrearCuenta' => 'Crear cuenta',
    'Enviar' => 'Enviar',
    'Trabaja' => '¡Únete a nosotros!',
    'SobreNosotros' => 'Sobre Nosotros',
    'IntroducirBusqueda' => 'Introduce aquí tu búsqueda',
    'ProximosCampeonatos' => 'Próximos Campeonatos',
));
$Navegacion = json(array(
    'Inicio' => 'Inicio',
    'Atras' => 'Atrás',
    'Anterior' => 'Anterior',
    'Siguiente' => 'Siguiente',
    'Tienda' => 'Tienda',
    'Noticias' => 'Noticias',
    'Club' => 'El Club',
    'Calendario' => 'Calendario',
    'Federacion' => 'FANJYDA',
    'LeerMas' => 'Leer más',
    'Login' => 'Iniciar Sesión',
    'Registro' => 'Registro',
    'LoginRegistro' => 'Login y registro',
    'Usuario' => 'Usuario',
    'Contra' => 'Contraseña',
    'Recuerdame' => 'recuerdame',
    'Registrate' => 'Registrate',
));
$Rutas = json(array(
    'Favicon' => 'site/images/logo/favicon.ico',
    'LogoW' => 'site/images/logo/logoW.png',
    'LogoXS' => 'site/images/logo/logoXS.png',
    'LogoS' => 'site/images/logo/logoS.png',
    'LogoM' => 'site/images/logo/logoM.png',
    'LogoL' => 'site/images/logo/logoL.png',
    'LogoXL' => 'site/images/logo/logoXL.png',
    'Bootstrap' => 'site/css/bootstrap.css',
    'Fonts' => 'site/css/fonts.css',
    'CSS' => 'site/css/style.css',
    'Index' => 'index.php',
    'Login' => 'login.php',

));

//include 'site/template/chat.php';
// esto es un apaño para sacar bonitos los datos
function json($parametros)
{
    return json_decode(json_encode($parametros));
}