image: "registry.romeronet.es/web-builder"

stages:
  - build
  - send-config-testing
  - deploy-testing
  - send-config
  - deploy

Build and push images:
  stage: build
  script:
    - sh ./cfg/scripts/build-and-push.sh

Send config to testing:
  stage: send-config-testing
  script:
    - sh ./cfg/scripts/generate-env-testing.sh
  only:
    - develop

Deploy to testing server:
  stage: deploy-testing
  script:
    - sh ./cfg/scripts/deploy-testing.sh
  environment:
    name: testing
    url: https://testing_kazoku.romeronet.es
  only:
    - develop

Send config to server:
  stage: send-config
  script:
    - sh ./cfg/scripts/generate-env.sh
  only:
    - master

Deploy to server:
  stage: deploy
  script:
    - sh ./cfg/scripts/deploy.sh
  environment:
    name: production
    url: https://kazoku.romeronet.es
  when: manual
  only:
    - master
