version: "3.4"
services:
  nginx:
    build:
      context: cfg
      dockerfile: docker-images/dev/nginx.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./src:/src"
      - "./public:/public"

  php-fpm:
    build:
      context: cfg
      dockerfile: docker-images/dev/php-fpm.Dockerfile
    environment:
      "KAZOKU_DATABASE_USER": "${KAZOKU_DATABASE_USER}"
      "KAZOKU_DATABASE_PASSWORD": "${KAZOKU_DATABASE_PASSWORD}"
      "KAZOKU_DATABASE_DATABASE": "${KAZOKU_DATABASE_DATABASE}"
      "KAZOKU_MAIL_USER": "${KAZOKU_MAIL_USER}"
      "KAZOKU_MAIL_PASSWORD": "${KAZOKU_MAIL_PASSWORD}"
    volumes:
      - "./src:/src"
      - "./public:/public"
      - "kazoku_composer_cache:/root/composer"

  db:
    image: mariadb:10.4
    volumes:
      - "kazoku_database_devel:/var/lib/mysql"
      - "./cfg/db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_USER:  ${KAZOKU_DATABASE_USER}
      MYSQL_PASSWORD: ${KAZOKU_DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${KAZOKU_DATABASE_DATABASE}
    ports:
      - "3306:3306"

  node:
    image: node:lts
    volumes:
      - ./web:/web
      - ./public:/public
volumes:
  kazoku_database_devel:
  kazoku_composer_cache:
